title: Agent Tools or Wrapper Agents?
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Enable Mermaid
mermaid:
  # Version of mermaid library to load
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1" # Or any other stable version you prefer, check the link above for the latest